NAME = SYED UMER AHMED
PROJECT NAME = HEALTH RISK CLASSFICATION
ROLL NUMBER=24F-AI-014

In [11]:
import kagglehub

path = kagglehub.dataset_download("jamaltariqcheema/pima-indians-diabetes-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'pima-indians-diabetes-dataset' dataset.
Path to dataset files: /kaggle/input/pima-indians-diabetes-dataset

In [12]:
import os
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

files = os.listdir(path)
print(files)

csv_file = [f for f in files if f.endswith('.csv')][0]
df = pd.read_csv(os.path.join(path, csv_file))

display(df.head())
print(df.info())

['diabetes.csv']

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 54.1 KB
None

In [13]:
missing_cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

df[missing_cols] = df[missing_cols].replace(0, np.nan)

for col in missing_cols:
    df[col] = df[col].fillna(df[col].median())

X = df.drop(columns=['Outcome'])
y = df['Outcome']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

print(df.isnull().sum())
display(X_scaled.head())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.639947,0.864625,-0.032180,0.665181,0.311604,0.169483,0.468492,1.425995
1,-0.844885,-1.204727,-0.528124,-0.010112,-0.440843,-0.848549,-0.365061,-0.190672
2,1.233880,2.014265,-0.693438,0.327535,0.311604,-1.328478,0.604397,-0.105584
3,-0.844885,-1.073339,-0.528124,-0.685405,-0.536303,-0.630399,-0.920763,-1.041549
4,-1.141852,0.503310,-2.677212,0.665181,0.294758,1.551096,5.484909,-0.020496

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)
svm = SVC(kernel='linear')

svm.fit(X_train, y_train)

svm_pred = svm.predict(X_test)

print("SVM Accuracy:", accuracy_score(y_test, svm_pred))
print("SVM Confusion Matrix:")
print(confusion_matrix(y_test, svm_pred))
print(classification_report(y_test, svm_pred))

tree = DecisionTreeClassifier(random_state=42)

tree.fit(X_train, y_train)

tree_pred = tree.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, tree_pred))
print("Decision Tree Confusion Matrix:")
print(confusion_matrix(y_test, tree_pred))
print(classification_report(y_test, tree_pred))

SVM Accuracy: 0.7575757575757576
SVM Confusion Matrix:
[[125  26]
 [ 30  50]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       151
           1       0.66      0.62      0.64        80

    accuracy                           0.76       231
   macro avg       0.73      0.73      0.73       231
weighted avg       0.76      0.76      0.76       231

Decision Tree Accuracy: 0.8484848484848485
Decision Tree Confusion Matrix:
[[130  21]
 [ 14  66]]
              precision    recall  f1-score   support

           0       0.90      0.86      0.88       151
           1       0.76      0.82      0.79        80

    accuracy                           0.85       231
   macro avg       0.83      0.84      0.84       231
weighted avg       0.85      0.85      0.85       231

In [15]:
svm_acc = accuracy_score(y_test, svm_pred)
tree_acc = accuracy_score(y_test, tree_pred)

print("SVM Accuracy:", svm_acc)
print("Decision Tree Accuracy:", tree_acc)

if svm_acc > tree_acc:
    print("SVM performed better.")
elif tree_acc > svm_acc:
    print("Decision Tree performed better.")
else:
    print("Both models performed equally.")

SVM Accuracy: 0.7575757575757576
Decision Tree Accuracy: 0.8484848484848485
Decision Tree performed better.

In [16]:
print("SVM Training Accuracy:", svm.score(X_train, y_train))
print("SVM Testing Accuracy:", svm.score(X_test, y_test))

print("Decision Tree Training Accuracy:", tree.score(X_train, y_train))
print("Decision Tree Testing Accuracy:", tree.score(X_test, y_test))

SVM Training Accuracy: 0.7932960893854749
SVM Testing Accuracy: 0.7575757575757576
Decision Tree Training Accuracy: 1.0
Decision Tree Testing Accuracy: 0.8484848484848485